server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: cloudconfig
  cloud:
    config:
      server:
        git:
         uri: C:/Users/Windows/Downloads/cloudConfig/Git/CloudConfig/
         
